---
- name: Create CLI directory
  file: path=/opt/rancher2-cli/ state=directory mode="a+rw"

- name: Get CLI.
  get_url:
    url: https://github.com/rancher/cli/releases/download/{{ rancher2_cli_version }}/rancher-linux-amd64-{{ rancher2_cli_version }}.tar.gz
    dest: "/opt/rancher2-cli/"
    mode: 0755

